name: Demo Workflow
on: # Trigger the workflow on push or pull request events to the main or dev branches
    push:
      branches: 
        - main
        - dev

    pull_request:
      branches: [main, dev]
    schedule:
        - cron: "*/1 * * * *"  # Runs every 1 minutes"

jobs:

   setup_job:
     runs-on: ubuntu-latest # macos-latest, windows-latest
     steps:
       - name: create a file 
         run: touch github-action.txt
       - name: print hello world
         run: echo "Hello, World!"
       - name: display readme file
         run: cat README.md
   
   
   
   
    build_job:
        runs-on: ubuntu-latest
        steps:
          - name: display hello
            run: echo "hello"


    deploy_job:
        runs-on: mac-latest
        steps:
          - run: echo "deploying...."


      
